### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by Connor-Walden** [alex-stew/project1#6]
Below is html and css for three cool fonts from google fonts... What do y'all think?

html:
link rel="preconnect" href="https://fonts.gstatic.com"

link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&family=Imbue&family=Yusei+Magic&display=swap" rel="stylesheet"

css:
font-family: 'Hachi Maru Pop', cursive;
font-family: 'Imbue', serif;
font-family: 'Yusei Magic', sans-serif;

**Comment by alex-stew** [comment]
raleway - p font
yusei magic - heading font (maybe), im leaning towards grabbing a font in the same fam as spotify or twitter fonts typeface
